name: dexcom_flutter_example
description: A simple app that demonstrates the use of dexcom_flutter.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ------- DEXCOM_FLUTTER 
  dexcom_flutter:
    path: ../
  # --------------------
    
  # ----- SHAREDPREFERENCES
  #shared_preferences: ^2.0.5
  # -----

  # ----- PROVIDER
  provider: ^6.0.5
  # -----

  # ----- GETIT
  #get_it: ^6.0.0
  # -----

  # ----- MOOR (for databases)
  moor: ^4.6.1+1 # use the latest version
  sqlite3_flutter_libs: ^0.5.13 # Also use the latest version.
  path_provider: ^2.0.13
  path: ^1.8.2
  # -----

  cupertino_icons: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # ----- MOOR 
  moor_generator: ^4.6.0+1 # use the latest version
  build_runner: ^2.3.3 
  # ----- 

# The following section is specific to Flutter.
flutter:
  uses-material-design: true