name: dexcom_flutter
description: A new Flutter package project.
version: 1.0.0-dev.1
homepage: https://github.com/gcappon/dexcom_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_web_auth: ^0.5.0 #used to implement oauth 2.0
  dio: ^5.0.3 #better web browser
  logger: ^1.3.0
  get_it: ^7.2.0
  shared_preferences: ^2.0.18
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
